# author 13
# qq-group 791509631
# email 2449207463@qq.com
# link https://github.com/newbee-ltd

# 服务器配置
server:
  port: 28079
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  servlet:
    session:
      tracking-modes: cookie

# 项目全局配置
project:
  # 项目名称
  name: newbee-mall-plus
  # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  fileUploadPath: ~/upload/
  # 订单未支付超期时间，单位秒
  orderUnpaidOverTime: 300
  # 服务器地址
  serverUrl: http://localhost:28079

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /admin/*,

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  session:
    timeout: 3600S
    redis:
      namespace: newbee-mall-plus:session

# mybatis配置
mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml

# xml 文件热加载
mybatis-xml-reload:
  enabled: false
  mapper-locations: classpath:mapper/*Mapper.xml

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
# https://open.alipay.com/develop/sandbox/account
# https://blog.csdn.net/qq_40276423/article/details/133301432
alipay:
  app-id: 9021000129639843
  rsa-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCj946eNBfDUsN/dmiKoxBKT8vf520Ixm9VxenxD586B+vVxBotac3baxKjRbFQawC0H58xi9YNdmc3/d0AAEggsaNXeAOp3tgRnLcaVHu7EoaEOlsT4rFvUWWaCC8wjP2C9Ix+sK+BC3bq/bY2glF1Mgoq7SHzemdVTD9msX+mwOmQKIVmKS+PdgTebuZe2T7VQI0FWlbvIlWsRrRUlTDVLy5laihwPVebqxKxoI/LBxO5Oo/6eXu67OCMV4AacWzoFhYzyyjOQ3IreUx/YjJuhH1XLwDiCAu0ITtOaz8EXX5gbmCZUOxT+eHTiwYOo+c+vFGq8JluocwaIsX/2fpVAgMBAAECggEANYFxLrr9DiYR2aRAFQ2FIVrMwrH4aKaoair9XkakxQEUulsV17/xByr3mAQECqQARMcU4cwp+5aptCHJXli5MMIG9WIaf/JSO90R+yuafL9c2gVY9zJAiHzdVNha3dMEXxmCR01M2CVvlttX/I2mG0JLAxsCuzs0QSdygQZnC3jegSrWd6OHmoyMajxscjEMLdKfpt5rAS2tKo1TiQ5lE5J74BX5Pt91G70r08OTFKmJg1L6thgMNU/Gti6dbQoqufQ6FgR62xrGMhuXiMiId/xR6zy1IpdDR4TAPbeKu3NXnN0721fAUETwEKiw7VEkxakV9p5KE5mHM/W/LaPzOQKBgQDQ/MuM+1llHTsUIrstO1SN3iVfV5dlrja0qVoUTce2m37eVT/m9xtbZmcFzYB6xCiEdZ0Uoz0kBAi4oS52EUOz+lvTOB6T22pUYYaLedNDR1WmI6jD+yfYY8ksmDiTnUagMK9+NabBBhzBj1TpRFT4lANKcA0+IW+E3VMpvcmojwKBgQDI2h3Lc1WtZ6ukfvpXNo6xsm8fGtXbcsHZFAlB4uqEIyRD3tMecAC7RBsXuaMsIICvbi0aUcSicQ5KqEcKtdhgOeVnFUKb5X5XQqkp+V8iF9PRiFbm/IN6mbjy+4iKR9JWGp6gl8PKP11TVlNZaJSrylOSPAKjmrjExAqu0dC42wKBgHMV4xn+CFqQYEpUXfMoqwV9AeOhHrRV3bZbVEm+E27R7mmNVKViCuSoXa9qXYg9oXpgMmJ9ClxdBFh4GlfWZgwkoJCOZPhTahiRpEAGlHqGO/pDxNo34tddDBnMsctIXu40IVBFR1EghpFo1v+mK4zAJZfGYOSIERt/rh5cb0KtAoGAFQYf0EgGU9xiLxnLgo2HajpPP2ZDtHDSsbJTNb5W5fX3udL9LlZy/Scn3tfjqJ7OWY6i0fp1JrvGzzHGHezi9U+aH6wuCLuA+glUQ7yCpMLxvSEUV6Fe8dpdbbG+nRrffXvT1uOL7wOq9So4F0fHKCRJkykM7asoZBBRPfNgcbkCgYBKikO8d+v4ONBEtg5+8WM7rtXFUM09G7cKU4OJzKEzJa6E/3bd0xejgCqYQ+05nkmzrlfBgCWozTAZCxPOYkCqeHXo49f1/34xqP5hlkpdnGTxNFWsmWDorub8rEWuvT6f6kDVjzY3HgJcT7FOjU8xXECwACs7Me2atPYZKlUYAg==
  alipay-public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/eOnjQXw1LDf3ZoiqMQSk/L3+dtCMZvVcXp8Q+fOgfr1cQaLWnN22sSo0WxUGsAtB+fMYvWDXZnN/3dAABIILGjV3gDqd7YEZy3GlR7uxKGhDpbE+Kxb1FlmggvMIz9gvSMfrCvgQt26v22NoJRdTIKKu0h83pnVUw/ZrF/psDpkCiFZikvj3YE3m7mXtk+1UCNBVpW7yJVrEa0VJUw1S8uZWoocD1Xm6sSsaCPywcTuTqP+nl7uuzgjFeAGnFs6BYWM8sozkNyK3lMf2IyboR9Vy8A4ggLtCE7Tms/BF1+YG5gmVDsU/nh04sGDqPnPrxRqvCZbqHMGiLF/9n6VQIDAQAB
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  format: JSON
  log-path: ./alipay-log/
  signtype: RSA2
